version: "3.5"

services:
  mongo:
    image: mongo:3
    ports:
      - 27017:27017
    tmpfs:
      - /data/db
    networks:
      - farm-net

  analyse:
    image: analysis-service:latest
    ports:
    - 8080:8080
    depends_on:
      - mongo
    networks:
      - farm-net

networks:
  farm-net:
    external:
      name: farm-net