version: "3.5"

services:
  mongo:
    image: mongo:3
    ports:
      - 27017:27017
    tmpfs:
      - /data/db

  analyse:
    image: analysis-service:latest
    ports:
    - 8080:8080
    depends_on:
      - mongo
